plugins {
    id 'java'
}

group 'com.macbein'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.0' // Use the latest version
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.0' // Use the latest version
}

test {
    useJUnitPlatform()
}
